### ISSUE TITLE
Script to get coordinates.

### ISSUE THREAD

**Issue by ACH1980** [jfbarras/slimy-snake#37]
Hey, I just wanted to ask, if you could help me building a script that get's the coordinates. I tried to disassemble your bot and write my own script based on the insights I got from this, but tbh I don't understand it really and just tried to copy and paste some lines and hoped it'll work as I intend.

I've written some basic JS, but I'm really better in PHP as I worked long time in backend only, I think when I've the basic to get the coordinates I should be able to understand how to interact with slither.io and would be able to code the rest of the needed code.

**Comment by jfbarras** [comment]
Hi.
Your snake's coordinates are printed in the bottom right corner.

            // Displays the X and Y of the snake.
            oContent.push(
                'x: ' + (Math.round(bot.xx) || 0) +
                ' y: ' + (Math.round(bot.yy) || 0));

bot.xx and bot.yy are computed every frame, as follows:

            bot.xx = window.snake.xx + window.snake.fx;
            bot.yy = window.snake.yy + window.snake.fy;

**Comment by ACH1980** [comment]
I've tried with this snippet, but it crashes my whole PC (not only the Browser):

```// ==UserScript==
// @name         Slither.io Dev-Script
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        *://slither.io/*
// @icon         data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==
// @grant        none
// ==/UserScript==


var bot = window.bot;

function coordinates() {
    if (window.snake) {
        bot.xx = window.snake.xx + window.snake.fx;
        bot.yy = window.snake.yy + window.snake.fy;

        console.log(bot.xx);
        console.log(bot.yy);
    }
}

while (true) {
    window.setTimeout(coordinates(bot), 1000)
}
```

**Comment by jfbarras** [comment]
Can't help you. Sorry.

**Comment by ACH1980** [comment]
Ok :(
